# Generated by Django 5.0.7 on 2024-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageApp', '0002_destination_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
    ]
